# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: javac ./p1MultiplesOf3And5/Problem1.java
      - run: java p1MultiplesOf3And5.Problem1

      - run: javac ./p2EvenFibonacciNumbers/Problem2.java
      - run: java p2EvenFibonacciNumbers.Problem2

      - run: javac ./p3LargestPrimeFactor/Problem3_int.java
      - run: java p3LargestPrimeFactor.Problem3_int

      - run: javac ./p3LargestPrimeFactor/Problem3_long.java
      - run: java p3LargestPrimeFactor.Problem3_long

      - run: javac ./p4LargestPalindromeProduct/Problem4.java
      - run: java p4LargestPalindromeProduct.Problem4

      - run: javac ./p5SmallestDivisibleNumber/Problem5.java
      - run: java p5SmallestDivisibleNumber.Problem5