# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_OPTS: -Xmx3200m

    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:fa:52:e9:c8:94:b1:72:81:11:c4:9e:cf:62:d9:22"

      - checkout

      - run: pwd
      - run: ls
      
      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p1multiplesof3and5/Problem1.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p1multiplesof3and5.Problem1

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p2evenfibonaccinumbers/Problem2.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p2evenfibonaccinumbers.Problem2

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p3largestprimefactor/Problem3_int.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p3largestprimefactor.Problem3_int

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p3largestprimefactor/Problem3_long.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p3largestprimefactor.Problem3_long

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p4largestpalindromeproduct/Problem4.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p4largestpalindromeproduct.Problem4

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p5smallestdivisiblenumber/Problem5.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p5smallestdivisiblenumber.Problem5

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p6sumsquaredifference/Problem6.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p6sumsquaredifference.Problem6

      - run: javac ./repo/src/main/java/com/github/james_flynn_ie/projecteulerjava/p7tenthousandandfirstprimenumber/Problem7.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p7tenthousandandfirstprimenumber.Problem7
