# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: javac ./p1MultiplesOf3And5/Problem1.java

      - run: ls -al ./p1MultiplesOf3And5 && java ./p1MultiplesOf3And5/Problem1.java

