# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p1multiplesof3and5/Problem1.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p1multiplesof3and5.Problem1

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p2evenfibonaccinumbers/Problem2.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p2evenfibonaccinumbers.Problem2

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p3largestprimefactor/Problem3_int.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p3largestprimefactor.Problem3_int

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p3largestprimefactor/Problem3_long.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p3largestprimefactor.Problem3_long

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p4largestpalindromeproduct/Problem4.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p4largestpalindromeproduct.Problem4

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p5smallestdivisiblenumber/Problem5.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p5smallestdivisiblenumber.Problem5

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p6SumSquareDifference/Problem6.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p6SumSquareDifference.Problem6

      - run: javac ./src/main/java/com/github/james_flynn_ie/projecteulerjava/p7TenThousandAndFirstPrimeNumber/Problem7.java
      - run: java src.main.java.com.github.james_flynn_ie.projecteulerjava.p7TenThousandAndFirstPrimeNumber.Problem7
